# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.CharField(max_length=100),
        ),
    ]
