# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='place',
            new_name='destination',
        ),
    ]
