# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20160903_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('description', models.CharField(max_length=300)),
                ('capital', models.CharField(max_length=30)),
            ],
        ),
    ]
