# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20160910_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.RemoveField(
            model_name='place',
            name='state_province',
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.CharField(max_length=800),
        ),
    ]
